[package]
name = "rustmd"
version = "0.1.0"
authors = ["lewin"]
edition = "2018"
description = "A tiny markdown compiler written in Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
